-- 메인 카테고리
INSERT INTO categories (name, created_at, updated_at) VALUES
    ('앨범', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('굿즈', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('포토카드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sub_categories (category_id, name, created_at, updated_at) VALUES
    (1, '미니앨범', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, '정규앨범', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, '싱글앨범', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sub_categories (category_id, name, created_at, updated_at) VALUES
    (2, '응원봉', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, '슬로건', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, '인형', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, '옷', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, '액세서리', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, '기타', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sub_categories (category_id, name, created_at, updated_at) VALUES
    (3, '앨범', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, '럭키드로우', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, '팬사인회', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, '시즌그리팅', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, '팬미팅', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, '콘서트', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'MD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, '콜라보', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, '팬클럽', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, '기타', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);